name: shovving_pre
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#structureÃ
  get: ^4.6.5
  shared_preferences: ^2.1.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
#UI
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  slide_action: ^0.0.2
  flutter_svg: ^2.0.5
#function
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  image_cropper: ^4.0.1
  flutter_sharing_intent: ^1.0.6
  html: ^0.15.4
  http: ^0.13.6
  string_validator: ^0.3.0
  url_launcher: ^6.1.11
  flutter_html: ^3.0.0-beta.2
  kakao_flutter_sdk: ^1.4.3
  flutter_naver_login: ^1.8.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.3
  flutter_native_splash: ^2.2.19
  flutter_inappwebview: ^5.7.2+3
  webview_flutter: ^4.2.2
  video_player: ^2.7.0
  path_provider: ^2.0.15
  rive: ^0.11.4
  dio: ^5.3.2
  device_info_plus: ^9.0.3
  android_id: ^0.3.3
  http_parser: ^4.0.2
  share_plus: ^7.1.0
  fk_user_agent: ^2.1.0
  cached_network_image: ^3.2.3
  sqflite: ^2.2.8+4
  flutter_launcher_icons: ^0.13.1
  flutter_icons: ^1.1.0
  mime: ^1.0.4
  dart_jsonwebtoken: ^2.8.0
  flutter_screenutil: ^5.7.0
  jwt_decoder: ^2.0.1
  restart_app: ^1.1.2
  photo_manager: ^2.7.1
  permission_handler: ^11.0.0
  flutter_image_compress: ^2.0.4
  clipboard: ^0.1.3
  firebase_messaging: ^14.7.8
  firebase_core: ^2.16.0
  flutter_local_notifications: ^15.1.1
  extended_text: ^10.0.1
  easy_refresh: ^3.3.2+4
  crypto: ^3.0.3
  encrypt: ^5.0.1
  change_app_package_name: ^1.1.0











dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - pubspec.yaml
    - assets/svgs/common/
    - assets/svgs/group/
    - assets/svgs/favicon/
    - assets/images/
    - assets/riv/
  fonts:
     - family: Spoqa-Bold
       fonts:
         - asset: assets/font/Spoqa_Han_Sans_Bold.ttf
     - family: Spoqa-Regular
       fonts:
         - asset: assets/font/Spoqa_Han_Sans_Regular.ttf
     - family: Neo-Bold
       fonts:
         - asset: assets/font/NanumSquareNeo-cBd.ttf
     - family: Neo-Regular
       fonts:
         - asset: assets/font/NanumSquareNeo-bRg.ttf
     - family: Neo-EBold
       fonts:
         - asset: assets/font/NanumSquareNeo-dEb.ttf
     - family: Neo-Light
       fonts:
         - asset: assets/font/NanumSquareNeo-aLt.ttf
     - family: Neo-Heavy
       fonts:
         - asset: assets/font/NanumSquareNeo-eHv.ttf


flutter_native_splash:
  image: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png
  color: "#FFFFFF"
#  fill: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/naemonemon_app_logo.png"